### ISSUE TITLE
with_thread: Use of serve in start script

### ISSUE THREAD

**Issue by allsey87** [ragingwind/wask-rust#3]
The command for the `serve` script is `cd ./dist && serve`, however nothing provides `serve`. Perhaps something is missing from `devDependencies`?

**Comment by ragingwind** [comment]
serve will be installed global at the build time. Did you get some error when you do the command?

**Comment by allsey87** [comment]
It's just not clear whether serve is something that has to be installed with Cargo, NPM, something else?

**Comment by ragingwind** [comment]
See https://github.com/ragingwind/webassembly-starter-kit-rust/blob/main/Dockerfile#L34
